name = "tikkle"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "tikkle-db"
database_id = "16ebeaf9-8c7d-4315-9f9f-0f547ce17edc"
preview_database_id = "e976992b-2f9c-4b3c-85df-d2b547f4781f"
migrations_dir = "drizzle"
